// <auto-generated />
namespace CMS_Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tablePin_editCol_Link_length500 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tablePin_editCol_Link_length500));
        
        string IMigrationMetadata.Id
        {
            get { return "201806150540027_tablePin_editCol_Link_length500"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
