// <auto-generated />
namespace CMS_Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addTbl_Log_mod_Context : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTbl_Log_mod_Context));
        
        string IMigrationMetadata.Id
        {
            get { return "201806200905164_addTbl_Log_mod_Context"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
